package com.securevault.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * User Entity
 *
 * @Entity  - marks this class as a JPA entity (maps to a database table)
 * @Table   - specifies the table name in PostgreSQL (will be "users")
 *
 * Hibernate will automatically create/update the "users" table
 * based on the fields defined here.
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Primary key - auto-incremented by the database.
     * IDENTITY strategy uses PostgreSQL's serial / GENERATED BY DEFAULT AS IDENTITY.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;

    /**
     * User's full name.
     * nullable = false means this column is required in the database.
     */
    @Column(nullable = false)
    private String name;

    /**
     * User's email address.
     * unique = true enforces that no two users share the same email.
     * nullable = false means this column is required in the database.
     */
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * User's password hash.
     *
     * This field stores the BCrypt hash of the user's password, NOT the plaintext password.
     * BCrypt automatically generates a unique salt for each hash, so two users with the
     * same password will have different hashes stored in the database.
     *
     * Example BCrypt hash: $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
     *
     * The database column name is "password_hash".
     */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    // ------------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------------

    /** No-argument constructor required by JPA/Hibernate. */
    public User() {
    }

    /** Convenience constructor to create a User with all fields. */
    public User(String name, String email, String passwordHash) {
        this.name = name;
        this.email = email;
        this.passwordHash = passwordHash;
    }

    // ------------------------------------------------------------------
    // Getters and Setters
    // ------------------------------------------------------------------

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
}
